"""Add subcategory to products

Revision ID: 77835e45fbeb
Revises: b26a7557717c
Create Date: 2026-03-13 13:44:12.695316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77835e45fbeb'
down_revision: Union[str, Sequence[str], None] = 'b26a7557717c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
