"""Add subcategories to categories

Revision ID: b26a7557717c
Revises: d68dddd8ccd3
Create Date: 2026-03-13 13:30:33.957824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26a7557717c'
down_revision: Union[str, Sequence[str], None] = 'd68dddd8ccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('subcategories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'subcategories')
    # ### end Alembic commands ###
