"""Add category, tags, and images columns

Revision ID: c95e01829ff0
Revises: 17fff6d3a8af
Create Date: 2026-02-25 12:24:54.696409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95e01829ff0'
down_revision: Union[str, Sequence[str], None] = '17fff6d3a8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'images')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
