"""Add origin column

Revision ID: d68dddd8ccd3
Revises: 608f6bba8514
Create Date: 2026-03-11 11:10:09.877712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68dddd8ccd3'
down_revision: Union[str, Sequence[str], None] = '608f6bba8514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('origin', sa.String(), nullable=True))
    op.create_index(op.f('ix_site_visits_origin'), 'site_visits', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_visits_origin'), table_name='site_visits')
    op.drop_column('site_visits', 'origin')
    # ### end Alembic commands ###
